version: "3.9"

services:

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis123

  config-service:
    image:   mahmoudmhd47/config-service:latest
    ports:
      - "8888:8888"

  discovery-service:
    image:   mahmoudmhd47/discovery-service:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  api-gateway:
    image:   mahmoudmhd47/api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - redis

  customer-service:
    image:   mahmoudmhd47/customer-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - discovery-service

  restaurant-service:
    image:   mahmoudmhd47/restaurant-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - discovery-service

  order-service:
    image:   mahmoudmhd47/order-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - rabbitmq

  delivery-service:
    image:   mahmoudmhd47/delivery-service:latest
    ports:
      - "8084:8084"
    depends_on:
      - postgres
      - rabbitmq

volumes:
  postgres_data: